#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    t = int(input().strip())
    if 1<=t<=10**4:
        for t_itr in range(t):
            n = int(input().strip())
            if 1<=n<=10**4:
                sum1=0
                sum2=0
                for i in range(1,n+1):
                    sum1=sum1+i
                    sum2=sum2+i*i
            
            print(sum1*sum1-sum2)
                    
        
